[2022-05-13 03:05:07,880] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2022-05-12T00:00:00+00:00 [queued]>
[2022-05-13 03:05:07,907] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2022-05-12T00:00:00+00:00 [queued]>
[2022-05-13 03:05:07,909] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-13 03:05:07,910] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-05-13 03:05:07,911] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-13 03:05:07,952] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): inaccurate> on 2022-05-12 00:00:00+00:00
[2022-05-13 03:05:07,965] {standard_task_runner.py:52} INFO - Started process 16130 to run task
[2022-05-13 03:05:07,975] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2022-05-12T00:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpig3kbg8r', '--error-file', '/tmp/tmpold2xzqr']
[2022-05-13 03:05:07,982] {standard_task_runner.py:80} INFO - Job 49: Subtask inaccurate
[2022-05-13 03:05:08,120] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2022-05-12T00:00:00+00:00 [running]> on host c0c6f6bf1c08
[2022-05-13 03:05:08,251] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-05-12T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-12T00:00:00+00:00
[2022-05-13 03:05:08,253] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-13 03:05:08,256] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2022-05-13 03:05:08,300] {subprocess.py:85} INFO - Output:
[2022-05-13 03:05:08,301] {subprocess.py:89} INFO - inaccurate
[2022-05-13 03:05:08,303] {subprocess.py:93} INFO - Command exited with return code 0
[2022-05-13 03:05:08,345] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20220512T000000, start_date=20220513T030507, end_date=20220513T030508
[2022-05-13 03:05:08,398] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-13 03:05:08,453] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
