[2022-05-15 21:58:12,046] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2022-05-13T00:00:00+00:00 [queued]>
[2022-05-15 21:58:12,069] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2022-05-13T00:00:00+00:00 [queued]>
[2022-05-15 21:58:12,070] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-15 21:58:12,071] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-05-15 21:58:12,073] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-15 21:58:12,095] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): inaccurate> on 2022-05-13 00:00:00+00:00
[2022-05-15 21:58:12,104] {standard_task_runner.py:52} INFO - Started process 83 to run task
[2022-05-15 21:58:12,119] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2022-05-13T00:00:00+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp5_p7zssg', '--error-file', '/tmp/tmpz8xnnz85']
[2022-05-15 21:58:12,121] {standard_task_runner.py:80} INFO - Job 61: Subtask inaccurate
[2022-05-15 21:58:12,269] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2022-05-13T00:00:00+00:00 [running]> on host c0c6f6bf1c08
[2022-05-15 21:58:12,356] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-05-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-13T00:00:00+00:00
[2022-05-15 21:58:12,359] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-15 21:58:12,361] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2022-05-15 21:58:12,397] {subprocess.py:85} INFO - Output:
[2022-05-15 21:58:12,400] {subprocess.py:89} INFO - inaccurate
[2022-05-15 21:58:12,401] {subprocess.py:93} INFO - Command exited with return code 0
[2022-05-15 21:58:12,459] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20220513T000000, start_date=20220515T215812, end_date=20220515T215812
[2022-05-15 21:58:12,506] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-15 21:58:12,553] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
