[2022-05-15 21:58:11,836] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2022-05-14T00:00:00+00:00 [queued]>
[2022-05-15 21:58:11,862] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2022-05-14T00:00:00+00:00 [queued]>
[2022-05-15 21:58:11,875] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-15 21:58:11,876] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-05-15 21:58:11,877] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-15 21:58:11,897] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): inaccurate> on 2022-05-14 00:00:00+00:00
[2022-05-15 21:58:11,907] {standard_task_runner.py:52} INFO - Started process 82 to run task
[2022-05-15 21:58:11,917] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2022-05-14T00:00:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmphnoc626c', '--error-file', '/tmp/tmpcn5tovft']
[2022-05-15 21:58:11,918] {standard_task_runner.py:80} INFO - Job 60: Subtask inaccurate
[2022-05-15 21:58:12,080] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2022-05-14T00:00:00+00:00 [running]> on host c0c6f6bf1c08
[2022-05-15 21:58:12,173] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-05-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-14T00:00:00+00:00
[2022-05-15 21:58:12,175] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-15 21:58:12,177] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2022-05-15 21:58:12,192] {subprocess.py:85} INFO - Output:
[2022-05-15 21:58:12,195] {subprocess.py:89} INFO - inaccurate
[2022-05-15 21:58:12,196] {subprocess.py:93} INFO - Command exited with return code 0
[2022-05-15 21:58:12,238] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20220514T000000, start_date=20220515T215811, end_date=20220515T215812
[2022-05-15 21:58:12,292] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-15 21:58:12,325] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
