[2022-05-09 23:41:10,904] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2022-05-08T00:00:00+00:00 [queued]>
[2022-05-09 23:41:10,926] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2022-05-08T00:00:00+00:00 [queued]>
[2022-05-09 23:41:10,927] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-09 23:41:10,928] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-05-09 23:41:10,929] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-09 23:41:10,955] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): inaccurate> on 2022-05-08 00:00:00+00:00
[2022-05-09 23:41:10,964] {standard_task_runner.py:52} INFO - Started process 81 to run task
[2022-05-09 23:41:10,970] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2022-05-08T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp7rwee87a', '--error-file', '/tmp/tmpj9bvjwlq']
[2022-05-09 23:41:10,973] {standard_task_runner.py:80} INFO - Job 28: Subtask inaccurate
[2022-05-09 23:41:11,064] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2022-05-08T00:00:00+00:00 [running]> on host c0c6f6bf1c08
[2022-05-09 23:41:11,161] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-05-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-08T00:00:00+00:00
[2022-05-09 23:41:11,163] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-09 23:41:11,164] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2022-05-09 23:41:11,177] {subprocess.py:85} INFO - Output:
[2022-05-09 23:41:11,181] {subprocess.py:89} INFO - inaccurate
[2022-05-09 23:41:11,183] {subprocess.py:93} INFO - Command exited with return code 0
[2022-05-09 23:41:11,224] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20220508T000000, start_date=20220509T234110, end_date=20220509T234111
[2022-05-09 23:41:11,267] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-09 23:41:11,318] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
